### ISSUE TITLE
PWA installation triggers for IOS(Safari, Chrome)

### ISSUE THREAD

**Issue by hQQn** [adueck/pwa-install-demo#1]
Are there any issues with normal operation in iOS (Safari, Firfox)?

https://firt.dev/pwa-2021/#pwa-installation-triggers

![image](https://user-images.githubusercontent.com/48381970/107527087-d76adc00-6bfb-11eb-9355-928b43360843.png)

Seeing this article, it seems to be impossible.

Do you know the issue?

**Comment by adueck** [comment]
I am not super familiar with iOS behavior, but I have noticed that once an app is installed (ie. added to the home screen) the update behavior is much different. It holds updates for longer, not just until the app is closed and opened again. I remember playing around with it a bit, and discovered some things but I can't remember what I could and couldn't get working.
