### ISSUE TITLE
not working in local network

### ISSUE THREAD

**Issue by abned08** [adueck/pwa-install-demo#2]
thank for this great work, I added to my project but

http://localhost:5000/ ----> working
http://192.168.1.6:5000/ ----> not working

is that normal? 
because I want to install my App in local network and allow the Android users who are connected to the wifi to install it

**Comment by adueck** [comment]
Hmm, sorry I don't know about this and I don't think it's a normal use case. From what I understand [service workers need to be served over https](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#setting_up_to_play_with_service_workers) not http. So I am surprised that even the first one works.
